schweitzpgi/f18

- lib/burnside/CMakeLists.txt
- lib/burnside/bridge.cc
- lib/burnside/convert-expr.cc
- lib/burnside/convert-expr.h
- lib/burnside/intrinsics.cc
- lib/burnside/intrinsics.h
The goal is to abstract which library is targeted while lowering the calls.
What matters in this commit is the exposed interface and the dynamic data structure that holds the runtime description.
The static description of the runtime used to feed this API is a dummy description. The long term goal is to share this knowledge with the folding code that uses runtime.
> Add a small framework to lower intrinsic calls to runtime calls.

- lib/burnside/convert-expr.cc
- lib/burnside/intrinsics.cc
- lib/burnside/intrinsics.h
Initial PR:
https://github.com/schweitzpgi/f18/pull/2
* std::string -> llvm::StringRef
* removed const& around mlir::Type
* Added comment about optional argument non handling
> Answer PR #2 comments

- lib/burnside/bridge.cc
- lib/burnside/bridge.h
- lib/burnside/builder.cc
- lib/burnside/builder.h
- lib/burnside/convert-expr.cc
- lib/burnside/intrinsics.cc
`mlir::ModuleManager` is not required anymore to hold the symbol table, `mlir::ModuleOp` can directly be used as to query symbols.
The `mlir::ModuleManager` is useful to create distinct temp names from a variable name, but it does not sync its symbol table automatically with the module it manages. Keeping a `ModuleManager`
in a high level context seems to be too risky.
For instance, there was currently a bug where function names were directly created in the Module but looked-up in the `ModuleManager` that could not find them.
> Removed mlir::ModuleManager from the bridge

- lib/burnside/convert-expr.cc
- lib/burnside/intrinsics.cc
- lib/burnside/intrinsics.h
+ Add a level of indirection in front of the facility describing runtime functions related to Fortran intrinsic functions. This level allows to select a code generation function depending on the generic intrinsic name. This is because not all Fortran intrinsic functions map to runtime functions and even when they do, they may not map one to one and may require generating some boilerplate.
+ Completely hide the implementation using an owning pointer. It did not bring anything to define implementation related class in the header. So only expose a simple interface.
+ All code implementation code is reorganized in three classes:
-> `RuntimeStaticDescription`: allows constexpr description of the runtime libraries.
-> `MathRuntimeLibrary`: maps a reified representation of runtime functions to …
> Refactor intrinsic function lowering facility

- lib/burnside/convert-expr.cc
The type passed to `InsertValueOp` and `ExtractValueOp` builder while lowering complex ops to FIR was not the one expected. I think the result type is the only thing needed. Currently, it was passed the operation type and mlir then seemed to take that for the result type which then created weird situation.
Example: Fortran complex constructor `z = (1., -1.)`
FIR dump before:
`%1 = fir.insert_value %0, %c0_i64 : (!fir.complex<8>, f64, i64) -> ((f64) -> !fir.complex<8>)`
FIR dump after:
`%4 = fir.insert_value %0, %c0_i64 : (!fir.complex<8>, f64, i64) -> !fir.complex<8>`
> fix type passed to InsertValueOp and ExtractValueOp builder

- lib/burnside/CMakeLists.txt
- lib/burnside/bridge.cc
- lib/burnside/complex.h
- lib/burnside/convert-expr.cc
- lib/burnside/flattened.cc
- lib/burnside/flattened.h
- lib/burnside/intrinsics.cc
- lib/burnside/io.cc
- lib/burnside/io.h
- lib/burnside/runtime.cc
- lib/burnside/runtime.h
This PR is a mix of several tasks I did last week. It is split in five commits with their own comments. Each commit is only dependent on the previous one this time (I tried to squash and rebase more cleverly).
Sumuary:
1. Move code generating FIR ops for Complex in their own class. This provide a more readable interface that can be use to manipulate complexes without repeating and depending on the boillerplate. 
2. Add root parse tree node to AnalysisData form flattening. This is to allow getting context information such as the function result symbol when generating FIR in the bridge. It also allows removing a few macros and narrowing the interface. Return Statement handling is improved in the bridge.
3. Lower user function call. Currently OK with implicit interface without need for …
> Funtion Result and Extraction of Maths Runtime for other runtime 

- lib/burnside/complex.h
- lib/burnside/convert-expr.cc
- lib/burnside/intrinsics.cc
- lib/burnside/runtime.cc
- lib/burnside/runtime.h
Address  PR #8 comments.
- Use template instead of bool inside complex to encode part
- Use Twine
- Other Editorial changes
Fix template bug with the empty `TypeCodeVector` (we may have runtime functions with no args, so this needs to work). I moved the "constexpr vector" aspect in its own class. In a way, it is also nicer because other things can now use it (it should probably go in `lib/common/constexpr-containers.h` with the constexpr multimap at some point).
> Address comments from PR #8 and fix template bugs

- lib/burnside/bridge.cc
- lib/burnside/builder.cc
- lib/burnside/builder.h
- lib/burnside/convert-expr.cc
- lib/burnside/fe-helper.cc
- lib/burnside/fe-helper.h
https://github.com/flang-compiler/f18/pull/788 changed many `const Symbol*` elements to `common::Reference<const Symbol>`  a.k.a. `SymbolRef` to indicate these pointers cannot be null.
This broke the bridge.
This PR both fixes the issue at the interface and also propagate the usage of `SymbolRef` inside the bridge to differentiate places where `Symbol*` can be nullptr or not.
> Fix symbol fallout

- lib/burnside/ast-builder.h
- lib/burnside/bridge.cc
- lib/burnside/convert-expr.cc
- lib/burnside/convert-expr.h
- lib/burnside/convert-type.cc
- lib/burnside/convert-type.h
This PR:
- Changes the ways logical are handled in the bridge  (core of the PR)
- Fixes a constant expression issue that came from last rebase with AST changes (not central, just to pass the build with clang).
Inside the `ExprLowering` facility:
- After evaluating an `Expr<Type<Logical, KIND>>` expression, convert the result to the type requested by the consumer of the expression if needed.
- A state `genLogicalAsI1` is added to `ExprLowering` facility. It allows to propagate the final consumer type through nodes where the type manipulated does not matter (e.g. parantheses) while also allowing a node of a tree to locally change the requested type to produce its logical operands.
At the external interface of `ExprLowering` facility:
- Add `createI1LogicalExpression` external methods that …
> Propagate logicals values in the type required by consumers

- lib/burnside/convert-expr.cc
- lib/burnside/convert-type.cc
- lib/burnside/convert-type.h
Address https://github.com/schweitzpgi/f18/pull/17 comments:
- Rename `genMLIRLogicalConstant` to `genLogicalConstantAsI1`
- Add assert that Fortran function calls have a single result in MLIR
- Editorial changes
Also apply logical type control around intrinsic and user function calls.
> Address PR17 review comments and control logical argument type

- lib/burnside/convert-expr.cc
- lib/burnside/intrinsics.cc
- MERGE: use MLIR `SelectOP`
- MIN/MAX: also use `SelectOp`. Provide different ways to
compare MIN/MAX operands to match existing behaviors
with NaNs. Use Minss/Maxss for now because it matches
ifort, nagfor and pgfortran -noillvm behavior.
- CONJG: use `fir::NegfOp` instead of a subtraction
- Comparisons: Changed Real comparisons to ordered comparisons
but for .NE. that remains UNE. This matches other compilers
behavior and is closer from Fortran 2018 table 17.1 requirements
in IEEE contexts.
Comments regarding failure to fulfill IEEE requirements regarding
the signaling/quiet aspect of the result for MIN/MAX/Comparisons
are added (Need llvm update or custom runtime support).
> MERGE lowering and MIN/MAX/CONJG/Comparisons lowering update

- lib/burnside/bridge.cc
- lib/burnside/convert-type.cc
- lib/burnside/convert-type.h
Not much in this PR, just paving the way for more character expression lowering:
- Use `fir.boxchar` for character dummy arguments
- Split assignment lowering into the different case to handle (character assignment is one). Also use new `typedAssignement` field that contain added implicit conversions/ defined assignment functions. (I saw that this field just changed recently (not yet in your branch), so this may break in the near future... sorry, I added a note).
> Lowering of Character Dummy for F77 interfaces

- lib/burnside/bridge.cc
- lib/burnside/convert-expr.cc
- lib/burnside/convert-type.cc
- lib/burnside/intrinsics.cc
This lowering of character assignment works for `c1 = c2` where:
- `c1` and `c2` are scalar variables with an explicit length (constant or dynamic).
- `c1` and `c2` do not overlap.
It handles the case where `c1` and `c2` do not have the same length.
The implementation is based on `fir.loop` and does not use any runtime. This
is more a proof of concept than a profound design choice.
After this commit, it is possible to lower to FIR and to get an functional
executable for:
```
SUBROUTINE foo(c1, c2, n)
INTEGER :: n
CHARACTER(n) :: c1
CHARACTER(10) :: c2
c1 = c2
END SUBROUTINE
```
FIXME/TODO are inserted for:
- The case where c1 or c2 is assumed length should "work" once rebased with
more up-do-date version of lib/evaluate, though `evaluate::DescriptorInquiry` will also need to be lowered …
> First part of scalar character assignment lowering

- lib/lower/bridge.cc
- lib/lower/convert-expr.cc
- lib/lower/convert-type.cc
- lib/lower/convert-type.h
- Lower `Ev::DescriptorInquiry` (only for inquiry about length of assumed character length (i.e. descriptor is a `fir::boxchar`)).
- Lower `Ev::Substring` address computation
> Implement substring and CHARACTER(*) assignment lowering

- lib/lower/bridge.cc
- lib/lower/convert-expr.cc
- lib/lower/intrinsics.cc
- lib/lower/intrinsics.h
Answer some comments from https://github.com/flang-compiler/f18/pull/920:
- Use std::unique_ptr for `IntrinsicLibrary::Implementation` instead of a simple "owning pointer" comment.
- Remove two `#if 0` dead code pieces
> Use std::unique_ptr for IntrinsicLibrary implementation

- README.md
- test-lit/CMakeLists.txt
- test-lit/lit.cfg.py
- test-lit/lit.site.cfg.py.in
- Fix flang path to export to lit config
- Add ".fir" extension in lit config to be considered as tests.
Tested with in-tree builds, it will probably still not work with out-of-tree builds due to llvm-lit paths issues.
PS: the result of the fir tests is a failure, but that is an actual know issue (not a test issue).
> Make flang lit test run with in-tree builds

- lib/Optimizer/Dialect/FIROps.cpp
Strings returned by `stringifyCmpFpredicate ` are not wrapped in `"`. That caused round trip test failures.
> Fix stringifyCmpFpredicate issue

- CMakeLists.txt
- test-lit/CMakeLists.txt
- test-lit/lit.site.cfg.py.in
- Fix clang + gnu ld `undefined reference to `main'` issue
- Fix paths to tco and bbc tools given to lit for out-of-tree builds
> Standalone cmake definition fixes

- lib/Optimizer/Support/InternalNames.cpp
That was the only significant difference in my fix.
> FIR mangling: use llvm::join to join module names

- CMakeLists.txt
- include/flang/Optimizer/Dialect/FIRDialect.h
- lib/Optimizer/CodeGen.cpp
- lib/Optimizer/StdConverter.cpp
- lib/Optimizer/Transforms/CSE.cpp
- lib/Optimizer/Transforms/RewriteLoop.cpp
4 MLIR changes had impact on FIR:
- https://github.com/llvm/llvm-project/commit/0ddba0bd59c337f16b51a00cb205ecfda46f97fa
`hasNoSideEffect` and `MemoryEffectOpInterface` seems to be functionnaly different, for instance
after changing only this, `return` were optimized out in the CSE pass.
Following the mlir commit example, it turned out `isOpTriviallyDead` now also has to be used
instead of `op->use_empty()` to remediate this.
- https://github.com/llvm/llvm-project/commit/7ca473a27bd589457d427eee9187d49a88fc9b01
MLIR cmake changes (Now we could use an out-of-tree MLIR also)
- https://github.com/llvm/llvm-project/commit/4d60f47b082f20d93f621fb5cd4bb978c26b7bf1
VectorOpsDialect renamed to VectorOp.
- https://github.com/llvm/llvm-project/commit/3145427dd73f0ee16dac4044890e2e2d2cae5040
Replace …
> [mlir rebase] changes to build along LLVM head 20th march 2020

- include/flang/Lower/FIRBuilder.h
- lib/Lower/Bridge.cpp
- lib/Lower/ConvertExpr.cpp
- lib/Lower/FIRBuilder.cpp
- lib/Lower/IO.cpp
- lib/Semantics/tools.cpp
- not-test/lower/test_character_assignment.sh
- test/Lower/pre-fir-tree02.f90
Go through function unit scope symbols and evaluate specification
expression before starting execution statements.
Current implementation only evaluate character length expression, and
hard TODO are added for other specification expressions.
CharacterOpsBuilder interface is cleaned up to support gettig stringLit.
Helper functions are also used in IO.cpp.
> Character Lowering update + Specification expression lowering skeleton

- include/flang/Semantics/symbol.h
- runtime/io-api.h
- test/lit.cfg.py
- test/lit.site.cfg.py.in
- tools/f18/CMakeLists.txt
Here are fixes for regressions I faced after the rebase.
Every tests now passes for me gcc out-of-tree and clang + libstdc++.
hello.f90 has issues with clang + libc++ builds  because the tests link to lstdc++ (at least when clang is not the default machine compiler, maybe this works on mac out of the box). I could not find a nice why to handle this without adding cmake complexity. Anyway, I did not fight because the issue is with the runtime that should not pull in libstdc++ to begin with (it's a regression after f18 changes to build on windows and changes to use llvm:raw_stream everywhere in f18).
> fixes after rebase with f18 5b89dc7 head
